### ISSUE TITLE
Error on the Run

### ISSUE THREAD

**Issue by vedhavyas** [Swatinem/fucov#1]
I'm seeing the following error on actions:
```
Run Swatinem/fucov@v1
(node:1595) UnhandledPromiseRejectionWarning: Error: The process '/usr/share/rust/.cargo/bin/rustc' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/Swatinem/fucov/v1/dist/index.js:1021:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/Swatinem/fucov/v1/dist/index.js:1004:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Swatinem/fucov/v1/dist/index.js:898:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:1595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any thoughts on how I can resolve this?

**Comment by Swatinem** [comment]
I think I was missing a catch block, so I added that along with updating dependencies.

Either way the cargo invocation above should print its output. Also, coverage reporting is still a nightly feature so might be unstable in itself.

**Comment by vedhavyas** [comment]
Cool. Will watch for new release 👍🏼
